FROM node:20

RUN npm install -g pnpm

WORKDIR /usr/app

COPY package.json .
COPY pnpm-lock.yaml .

RUN pnpm install

COPY ./prisma ./prisma

RUN npx prisma generate

COPY . .

EXPOSE 4200

CMD ["pnpm", "run", "start:dev"]